apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: telemeter-rules
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: PrometheusRule
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rules
      app.kubernetes.io/name: telemeter
      app.kubernetes.io/part-of: rhobs
      operator.thanos.io/prometheus-rule: "true"
      tenant: FB870BF3-9F3A-44FF-9BF7-D7A047A52F43
    name: telemeter-rules
    namespace: rhobs-stage
  spec:
    groups:
    - interval: 4m
      name: telemeter-telemeter.rules
      rules:
      - expr: count_over_time(vector(1)[1h:5m])
        record: steps:count1h
      - expr: count by (name, reason) (cluster_operator_conditions{condition="Degraded"}
          = 1)
        record: name_reason:cluster_operator_degraded:count
      - expr: count by (name, reason) (cluster_operator_conditions{condition="Available"}
          = 0)
        record: name_reason:cluster_operator_unavailable:count
      - expr: sort_desc(max by (_id, code) (code:apiserver_request_count:rate:sum{code=~"(4|5)\\d\\d"}
          > 0.5))
        record: id_code:apiserver_request_error_rate_sum:max
      - expr: |-
          bottomk by (_id) (
            1,
              max by (_id, version) (cluster_version{type="failure"} * 0)
            or
              max by (_id, version) (1 + cluster_version{type="current"} * 0)
          )
        record: id_version:cluster_available
      - expr: |-
          topk(
            1,
                    max by (_id, managed, ebs_account, internal) (
                      label_replace(
                        label_replace(
                          ocm_subscription{support=~"Standard|Premium|Layered"} * 0 + 1 or ocm_subscription * 0,
                          "internal",
                          "true",
                          "email_domain",
                          "redhat.com|(.*\\\\.|^)ibm.com"
                        ),
                        "managed",
                        "",
                        "managed",
                        "false"
                      )
                    )
                  + on (_id) group_left (version)
                    topk by (_id) (1, id_version * 0)
                + on (_id) group_left (install_type)
                  topk by (_id) (1, id_install_type * 0)
              + on (_id) group_left (host_type)
                topk by (_id) (1, id_primary_host_type * 0)
            + on (_id) group_left (provider)
              topk by (_id) (1, id_provider * 0)
          )
        record: id_version_ebs_account_internal:cluster_subscribed
