apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: servicemonitors
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: compactor
      app.kubernetes.io/created-by: lokistack-controller
      app.kubernetes.io/instance: observatorium-lokistack
      app.kubernetes.io/managed-by: lokistack-controller
      app.kubernetes.io/name: lokistack
      prometheus: app-sre
    name: loki-compactor-http
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: compactor
        app.kubernetes.io/created-by: lokistack-controller
        app.kubernetes.io/instance: observatorium-lokistack
        app.kubernetes.io/managed-by: lokistack-controller
        app.kubernetes.io/name: lokistack
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: distributor
      app.kubernetes.io/created-by: lokistack-controller
      app.kubernetes.io/instance: observatorium-lokistack
      app.kubernetes.io/managed-by: lokistack-controller
      app.kubernetes.io/name: lokistack
      prometheus: app-sre
    name: loki-distributor-http
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: distributor
        app.kubernetes.io/created-by: lokistack-controller
        app.kubernetes.io/instance: observatorium-lokistack
        app.kubernetes.io/managed-by: lokistack-controller
        app.kubernetes.io/name: lokistack
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: index-gateway
      app.kubernetes.io/created-by: lokistack-controller
      app.kubernetes.io/instance: observatorium-lokistack
      app.kubernetes.io/managed-by: lokistack-controller
      app.kubernetes.io/name: lokistack
      prometheus: app-sre
    name: loki-index-gateway-http
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: index-gateway
        app.kubernetes.io/created-by: lokistack-controller
        app.kubernetes.io/instance: observatorium-lokistack
        app.kubernetes.io/managed-by: lokistack-controller
        app.kubernetes.io/name: lokistack
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: ingester
      app.kubernetes.io/created-by: lokistack-controller
      app.kubernetes.io/instance: observatorium-lokistack
      app.kubernetes.io/managed-by: lokistack-controller
      app.kubernetes.io/name: lokistack
      prometheus: app-sre
    name: loki-ingester-http
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: ingester
        app.kubernetes.io/created-by: lokistack-controller
        app.kubernetes.io/instance: observatorium-lokistack
        app.kubernetes.io/managed-by: lokistack-controller
        app.kubernetes.io/name: lokistack
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: querier
      app.kubernetes.io/created-by: lokistack-controller
      app.kubernetes.io/instance: observatorium-lokistack
      app.kubernetes.io/managed-by: lokistack-controller
      app.kubernetes.io/name: lokistack
      prometheus: app-sre
    name: loki-querier-http
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: querier
        app.kubernetes.io/created-by: lokistack-controller
        app.kubernetes.io/instance: observatorium-lokistack
        app.kubernetes.io/managed-by: lokistack-controller
        app.kubernetes.io/name: lokistack
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/created-by: lokistack-controller
      app.kubernetes.io/instance: observatorium-lokistack
      app.kubernetes.io/managed-by: lokistack-controller
      app.kubernetes.io/name: lokistack
      prometheus: app-sre
    name: loki-query-frontend-http
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: query-frontend
        app.kubernetes.io/created-by: lokistack-controller
        app.kubernetes.io/instance: observatorium-lokistack
        app.kubernetes.io/managed-by: lokistack-controller
        app.kubernetes.io/name: lokistack
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: thanos-compactor
      app.kubernetes.io/instance: thanos-compact-rhobs
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-compact
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/owner: rhobs
      prometheus: app-sre
    name: thanos-compact-rhobs
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: thanos-compactor
        app.kubernetes.io/instance: thanos-compact-rhobs
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-compact
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: rhobs
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: thanos-compactor
      app.kubernetes.io/instance: thanos-compact-telemeter
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-compact
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/owner: telemeter
      prometheus: app-sre
    name: thanos-compact-telemeter
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: thanos-compactor
        app.kubernetes.io/instance: thanos-compact-telemeter
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-compact
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: telemeter
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/created-by: thanos-operator
      app.kubernetes.io/instance: controller-manager-metrics
      app.kubernetes.io/managed-by: rhobs
      app.kubernetes.io/name: servicemonitor
      app.kubernetes.io/part-of: thanos-operator
      prometheus: app-sre
    name: thanos-operator-controller-manager-metrics
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      path: /metrics
      port: https
      scheme: https
      tlsConfig:
        ca: {}
        cert: {}
        insecureSkipVerify: true
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        control-plane: controller-manager
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/instance: thanos-query-frontend-rhobs
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-query-frontend
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/owner: rhobs
      operator.thanos.io/query-api: "true"
      prometheus: app-sre
    name: thanos-query-frontend-rhobs
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: query-frontend
        app.kubernetes.io/instance: thanos-query-frontend-rhobs
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-query-frontend
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: rhobs
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: thanos-query-rhobs
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-query
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/owner: rhobs
      operator.thanos.io/query-api: "true"
      prometheus: app-sre
    name: thanos-query-rhobs
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: query-layer
        app.kubernetes.io/instance: thanos-query-rhobs
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-query
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: rhobs
        operator.thanos.io/query-api: "true"
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: thanos-receive-ingester
      app.kubernetes.io/instance: thanos-receive-ingester-rhobs-default
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-receive
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/owner: rhobs
      operator.thanos.io/store-api: "true"
      prometheus: app-sre
    name: thanos-receive-ingester-rhobs-default
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: thanos-receive-ingester
        app.kubernetes.io/instance: thanos-receive-ingester-rhobs-default
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-receive
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: rhobs
        operator.thanos.io/store-api: "true"
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: thanos-receive-ingester
      app.kubernetes.io/instance: thanos-receive-ingester-rhobs-telemeter
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-receive
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/owner: rhobs
      operator.thanos.io/store-api: "true"
      prometheus: app-sre
    name: thanos-receive-ingester-rhobs-telemeter
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: thanos-receive-ingester
        app.kubernetes.io/instance: thanos-receive-ingester-rhobs-telemeter
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-receive
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: rhobs
        operator.thanos.io/store-api: "true"
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: thanos-receive-router
      app.kubernetes.io/instance: thanos-receive-router-rhobs
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-receive
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/owner: rhobs
      prometheus: app-sre
    name: thanos-receive-router-rhobs
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: thanos-receive-router
        app.kubernetes.io/instance: thanos-receive-router-rhobs
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-receive
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: rhobs
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: object-storage-gateway
      app.kubernetes.io/instance: thanos-store-default
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-store
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/endpoint-group: "true"
      operator.thanos.io/owner: default
      operator.thanos.io/store-api: "true"
      prometheus: app-sre
    name: thanos-store-default
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: object-storage-gateway
        app.kubernetes.io/instance: thanos-store-default
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-store
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: default
        operator.thanos.io/store-api: "true"
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: object-storage-gateway
      app.kubernetes.io/instance: thanos-store-telemeter-0to2w
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-store
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/endpoint-group: "true"
      operator.thanos.io/owner: telemeter-0to2w
      operator.thanos.io/store-api: "true"
      prometheus: app-sre
    name: thanos-store-telemeter-0to2w
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: object-storage-gateway
        app.kubernetes.io/instance: thanos-store-telemeter-0to2w
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-store
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: telemeter-0to2w
        operator.thanos.io/store-api: "true"
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: object-storage-gateway
      app.kubernetes.io/instance: thanos-store-telemeter-2wto90d
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-store
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/endpoint-group: "true"
      operator.thanos.io/owner: telemeter-2wto90d
      operator.thanos.io/store-api: "true"
      prometheus: app-sre
    name: thanos-store-telemeter-2wto90d
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: object-storage-gateway
        app.kubernetes.io/instance: thanos-store-telemeter-2wto90d
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-store
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: telemeter-2wto90d
        operator.thanos.io/store-api: "true"
  status: {}
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: object-storage-gateway
      app.kubernetes.io/instance: thanos-store-telemeter-90dplus
      app.kubernetes.io/managed-by: thanos-operator
      app.kubernetes.io/name: thanos-store
      app.kubernetes.io/part-of: thanos
      operator.thanos.io/endpoint-group: "true"
      operator.thanos.io/owner: telemeter-90dplus
      operator.thanos.io/store-api: "true"
      prometheus: app-sre
    name: thanos-store-telemeter-90dplus
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - interval: 30s
      path: /metrics
      port: http
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: object-storage-gateway
        app.kubernetes.io/instance: thanos-store-telemeter-90dplus
        app.kubernetes.io/managed-by: thanos-operator
        app.kubernetes.io/name: thanos-store
        app.kubernetes.io/part-of: thanos
        operator.thanos.io/owner: telemeter-90dplus
        operator.thanos.io/store-api: "true"
  status: {}
