apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: synthetics-api-service-monitor
objects:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
      prometheus: app-sre
    name: synthetics-api
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: metrics
    namespaceSelector:
      matchNames:
      - rhobs-stage
    selector:
      matchLabels:
        app.kubernetes.io/component: synthetics-api
        app.kubernetes.io/instance: rhobs
        app.kubernetes.io/name: synthetics-api
        app.kubernetes.io/part-of: rhobs
        app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
  status: {}
