apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: synthetics-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
    name: synthetics-api
    namespace: rhobs-stage
  spec:
    clusterIP: None
    ports:
    - name: synthetics-api
      port: 11211
      protocol: TCP
      targetPort: 11211
    selector:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
    name: synthetics-api
    namespace: rhobs-stage
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
    name: synthetics-api
    namespace: rhobs-stage
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: synthetics-api
        app.kubernetes.io/instance: rhobs
        app.kubernetes.io/name: synthetics-api
        app.kubernetes.io/part-of: rhobs
        app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
    serviceName: synthetics-api
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: synthetics-api
          app.kubernetes.io/instance: rhobs
          app.kubernetes.io/name: synthetics-api
          app.kubernetes.io/part-of: rhobs
          app.kubernetes.io/version: cea7d4656cd0ad338e580cc6ba266264a9938e5c
      spec:
        containers:
        - image: quay.io/redhat-services-prod/openshift/rhobs-synthetics-api:cea7d4656cd0ad338e580cc6ba266264a9938e5c
          imagePullPolicy: IfNotPresent
          name: synthetics-api
          ports:
          - containerPort: 11211
            name: synthetics-api
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePolicy: FallbackToLogsOnError
        securityContext: {}
        serviceAccountName: synthetics-api
    updateStrategy: {}
  status:
    availableReplicas: 0
    replicas: 0
