apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: thanos-object-store-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: observatorium-mst-thanos-objectstorage
    name: observatorium-mst-thanos-objectstorage
    namespace: rhobs-int
  stringData:
    thanos.yaml: |
      type: S3
      config:
        bucket: ${S3_BUCKET_NAME}
        endpoint: ${S3_BUCKET_ENDPOINT}
        region: ${S3_BUCKET_REGION}
        disable_dualstack: false
        aws_sdk_auth: false
        access_key: ${ACCESS_KEY_ID}
        insecure: false
        signature_version2: false
        secret_key: ${SECRET_ACCESS_KEY}
        session_token: ""
        put_user_metadata: {}
        http_config:
          idle_conn_timeout: 0s
          response_header_timeout: 0s
          insecure_skip_verify: false
          tls_handshake_timeout: 0s
          expect_continue_timeout: 0s
          max_idle_conns: 0
          max_idle_conns_per_host: 0
          max_conns_per_host: 0
          tls_config:
            ca_file: ""
            cert_file: ""
            key_file: ""
            server_name: ""
            insecure_skip_verify: false
          disable_compression: false
        trace:
          enable: false
        list_objects_version: ""
        bucket_lookup_type: auto
        send_content_md5: false
        disable_multipart: false
        part_size: 0
        sse_config:
          type: ""
          kms_key_id: ""
          kms_encryption_context: {}
          encryption_key: ""
        sts_endpoint: ""
        max_retries: 0
      prefix: ""
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: thanos-bucket-cache-memcached
    name: thanos-bucket-cache-memcached
    namespace: rhobs-int
  stringData:
    thanos.yaml: |
      type: MEMCACHED
      config:
        addresses:
        - dnssrv+_client._tcp.thanos-bucket-cache.rhobs-int.svc
        timeout: 2s
        max_idle_connections: 1100
        max_async_concurrency: 50
        max_async_buffer_size: 25000
        max_get_multi_concurrency: 1000
        max_item_size: 1048576
        max_get_multi_batch_size: 100
        dns_provider_update_interval: 10s
        auto_discovery: false
        set_async_circuit_breaker_config:
          enabled: false
          half_open_max_requests: 0
          open_duration: 0s
          min_requests: 0
          consecutive_failures: 0
          failure_percent: 0
      chunk_subrange_size: 16000
      max_chunks_get_range_requests: 3
      metafile_max_size: 1048576
      chunk_object_attrs_ttl: 24h0m0s
      chunk_subrange_ttl: 24h0m0s
      blocks_iter_ttl: 0s
      metafile_exists_ttl: 2h0m0s
      metafile_doesnt_exist_ttl: 15m0s
      metafile_content_ttl: 24h0m0s
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: thanos-index-cache-memcached
    name: thanos-index-cache-memcached
    namespace: rhobs-int
  stringData:
    thanos.yaml: |
      type: MEMCACHED
      config:
        addresses:
        - dnssrv+_client._tcp.thanos-index-cache.rhobs-int.svc
        timeout: 2s
        max_idle_connections: 2500
        max_async_concurrency: 1000
        max_async_buffer_size: 2500000
        max_get_multi_concurrency: 1000
        max_item_size: 5242880
        max_get_multi_batch_size: 100000
        dns_provider_update_interval: 10s
        auto_discovery: false
        set_async_circuit_breaker_config:
          enabled: false
          half_open_max_requests: 0
          open_duration: 0s
          min_requests: 0
          consecutive_failures: 0
          failure_percent: 0
      enabled_items: []
      ttl: 0s
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: thanos-query-range-cache-memcached
    name: thanos-query-range-cache-memcached
    namespace: rhobs-int
  stringData:
    thanos.yaml: |
      type: MEMCACHED
      config:
        addresses:
        - dnssrv+_client._tcp.thanos-query-range-cache.rhobs-int.svc
        timeout: 5s
        max_idle_connections: 500
        max_async_concurrency: 100
        max_async_buffer_size: 1000000
        max_get_multi_concurrency: 100
        max_item_size: 104857600
        max_get_multi_batch_size: 500
        dns_provider_update_interval: 30s
        auto_discovery: false
        set_async_circuit_breaker_config:
          enabled: false
          half_open_max_requests: 0
          open_duration: 0s
          min_requests: 0
          consecutive_failures: 0
          failure_percent: 0
        expiration: 0s
  type: Opaque
parameters:
- name: S3_BUCKET_NAME
- name: S3_BUCKET_REGION
- name: S3_BUCKET_ENDPOINT
- name: ACCESS_KEY_ID
- name: SECRET_ACCESS_KEY
