apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: perses-operator-manager
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: kube-rbac-proxy
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: controller-manager-metrics-service
      app.kubernetes.io/name: service
      app.kubernetes.io/part-of: perses-operator
      control-plane: controller-manager
    name: perses-operator-controller-manager-metrics-service
    namespace: rhobs-int
  spec:
    ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      control-plane: controller-manager
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: manager
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: controller-manager
      app.kubernetes.io/name: deployment
      app.kubernetes.io/part-of: perses-operator
      control-plane: controller-manager
    name: perses-operator-controller-manager
    namespace: rhobs-int
  spec:
    replicas: 1
    selector:
      matchLabels:
        control-plane: controller-manager
    strategy: {}
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/default-container: manager
        creationTimestamp: null
        labels:
          control-plane: controller-manager
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - arm64
                  - ppc64le
                  - s390x
                - key: kubernetes.io/os
                  operator: In
                  values:
                  - linux
        containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=0
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:98455d503b797b6b02edcfd37045c8fab0796b95ee5cf4cfe73b221a07e805f0
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
        - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8082
          - --leader-elect
          image: https://quay.io/repository/redhat-user-workloads/rhobs-mco-tenant/rhobs-konflux-perses-operator:61d16ecf340f0d0ed79d89968ff59f11ade4bef6
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
        serviceAccountName: perses-operator-controller-manager
        terminationGracePeriodSeconds: 10
  status: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: controller-manager
      app.kubernetes.io/name: serviceaccount
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-controller-manager
    namespace: rhobs-int
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: leader-election-role
      app.kubernetes.io/name: role
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-leader-election-role
    namespace: rhobs-int
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: leader-election-rolebinding
      app.kubernetes.io/name: rolebinding
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-leader-election-rolebinding
    namespace: rhobs-int
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: perses-operator-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: perses-operator-controller-manager
    namespace: rhobs-int
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    name: perses-operator-manager-role
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    - statefulsets
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
  - apiGroups:
    - ""
    resources:
    - services
    - configmaps
    - secrets
    verbs:
    - get
    - patch
    - update
    - create
    - delete
    - list
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - perses
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - perses/finalizers
    verbs:
    - update
  - apiGroups:
    - perses.dev
    resources:
    - perses/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - perses.dev
    resources:
    - persesdashboards
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - persesdashboards/finalizers
    verbs:
    - update
  - apiGroups:
    - perses.dev
    resources:
    - persesdashboards/status
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - perses.dev
    resources:
    - persesdatasources
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - persesdatasources/finalizers
    verbs:
    - update
  - apiGroups:
    - perses.dev
    resources:
    - persesdatasources/status
    verbs:
    - get
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: manager-rolebinding
      app.kubernetes.io/name: clusterrolebinding
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-manager-rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: perses-operator-manager-role
  subjects:
  - kind: ServiceAccount
    name: perses-operator-controller-manager
    namespace: rhobs-int
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: kube-rbac-proxy
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: metrics-reader
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-metrics-reader
  rules:
  - nonResourceURLs:
    - /metrics
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: perses-editor-role
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-perses-editor-role
  rules:
  - apiGroups:
    - perses.dev
    resources:
    - perses
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - perses/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: perses-viewer-role
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-perses-viewer-role
  rules:
  - apiGroups:
    - perses.dev
    resources:
    - perses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - perses/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: persesdashboard-editor-role
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-persesdashboard-editor-role
  rules:
  - apiGroups:
    - perses.dev
    resources:
    - persesdashboards
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - persesdashboards/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: persesdashboard-viewer-role
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-persesdashboard-viewer-role
  rules:
  - apiGroups:
    - perses.dev
    resources:
    - persesdashboards
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - persesdashboards/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: persesdatasource-editor-role
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-persesdatasource-editor-role
  rules:
  - apiGroups:
    - perses.dev
    resources:
    - persesdatasources
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - persesdatasources/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: persesdatasource-viewer-role
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-persesdatasource-viewer-role
  rules:
  - apiGroups:
    - perses.dev
    resources:
    - persesdatasources
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - perses.dev
    resources:
    - persesdatasources/status
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: kube-rbac-proxy
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: proxy-role
      app.kubernetes.io/name: clusterrole
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-proxy-role
  rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - authorization.k8s.io
    resources:
    - subjectaccessreviews
    verbs:
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: rbac
      app.kubernetes.io/created-by: perses-operator
      app.kubernetes.io/instance: manager-rolebinding
      app.kubernetes.io/name: clusterrolebinding
      app.kubernetes.io/part-of: perses-operator
    name: perses-operator-proxy-rolebinding
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: perses-operator-proxy-role
  subjects:
  - kind: ServiceAccount
    name: perses-operator-controller-manager
    namespace: rhobs-int
