{
 "title": "API / Logs",
 "description": "The Observatorium API is the entrypoint for read and push log requests",
 "tags": [
  "observatorium",
  "observatorium-logs"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "handler",
    "query": "label_values(http_requests_total{job=\"observatorium-observatorium-mst-api\", group=\"logsv1\", namespace=\"$namespace\"}, handler)"
   }
  ]
 },
 "panels": [
  {
   "title": "/query & /labels & /label_values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Availability 1s [28d] > 95%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\",le=\"1\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\"}[28d]))"
    }
   ]
  },
  {
   "title": "Availability 5s [28d] > 99%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query\",le=\"5\",code!~\"5..\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query\"}[28d]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\",code=~\"5..\"}[5m]))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\",code!~\"5..\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\",code!~\"5..\"}[5m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query|label|labels|label_values\",code!~\"5..\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "/query_range", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Availability 60s [28d] > 90%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{group=\"logsv1\",handler=\"query_range\",le=\"60\",code!~\"5..\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{group=\"logsv1\",handler=\"query_range\"}[28d]))"
    }
   ]
  },
  {
   "title": "Availability 120s [28d] > 99%",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{group=\"logsv1\",handler=\"query_range\",le=\"120\",code!~\"5..\"}[28d]))\n/\nsum(increase(http_request_duration_seconds_count{group=\"logsv1\",handler=\"query_range\"}[28d]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query_range\"}[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query_range\",code=~\"5..\"}[5m])) / \nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query_range\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",code!~\"5..\",handler=\"query_range\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",code!~\"5..\",handler=\"query_range\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",code!~\"5..\",handler=\"query_range\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "RED for $handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "handler" },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code=~\"5..\"}[5m]))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "RED for $handler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_total{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code=~\"5..\"}[5m]))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\", namespace=\"$namespace\", group=\"logsv1\", handler=~\"$handler\",code!~\"5..\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}
{
 "title": "Loki / Operational",
 "tags": [
  "loki",
  "observatorium",
  "observatorium-logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(loki_request_duration_seconds_count{  route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pushes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n          rate(loki_request_duration_seconds_count{  route=~\"api_prom_push|loki_api_v1_push\"}[5m]),\n   \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bad Words",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (name,level) (rate(promtail_custom_bad_words_total{ exported_namespace=\"$namespace\"}[$__interval])) - \nsum by (name,level) (rate(promtail_custom_bad_words_total{ exported_namespace=\"$namespace\"}[$__interval] offset 1h)))",
     "legendFormat": "{{name}}-{{level}}"
    }
   ]
  },
  {
   "title": "Lines Per Tenant (top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_lines_received_total{ namespace=\"$namespace\"}[5m])) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "MBs Per Tenant (Top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_bytes_received_total{ namespace=\"$namespace\"}[5m])) by (tenant)) / 1024 / 1024",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{container=~\"observatorium-loki.+\", namespace=\"$namespace\"}[10m]) > 0",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{ route=~\"api_prom_push|loki_api_v1_push\"}))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{ route=~\"api_prom_push|loki_api_v1_push\"}))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{ route=~\"api_prom_push|loki_api_v1_push\"}))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-distributor-http\"}))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-distributor-http\"}))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-distributor-http\"}))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"}))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"}))",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"}))",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", status_code!~\"5[0-9]{2}\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.5"
    }
   ]
  },
  {
   "title": "Querier Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Querier Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}))",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}))",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}))",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", status_code!~\"5[0-9]{2}\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discarded Lines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant, reason) (rate(loki_discarded_samples_total{namespace=\"$namespace\"}[1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    },
    {
     "title": "Discarded Lines Per Interval",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "topk(10, sum by (tenant, reason) (sum_over_time(increase(loki_discarded_samples_total{namespace=\"$namespace\"}[1m])[$__range:1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\", pod=~\".*distributor.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{ namespace=\"$namespace\", pod=~\".*distributor.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"} | logfmt | level=\"error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"} |= \"level=error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"}[$__rate_interval])) by (route) > 0",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Append Failures By Ingester",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_append_failures_total{ namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Bytes Received/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{ namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Lines Received/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total{ namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\", pod=~\".*ingester.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{ namespace=\"$namespace\", pod=~\".*ingester.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "graph",
     "gridPos": { "h": 3, "w": 18, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\"} | logfmt | level=\"error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 18, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\"} |= \"level=error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\"}[$__rate_interval])) by (route) > 0",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Streams",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant) (loki_ingester_memory_streams{job=\"observatorium-loki-ingester-http\"}))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Streams Created/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (tenant) (rate(loki_ingester_streams_created_total{job=\"observatorium-loki-ingester-http\"}[1m]) > 0))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunks Flushed/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "Chunks"
      },
      {
       "expr": "sum(increase(loki_chunk_store_deduped_chunks_total{ job=\"observatorium-loki-ingester-http\"}[1m]))/sum(increase(loki_ingester_chunks_flushed_total{ job=\"observatorium-loki-ingester-http\"}[1m])) < 1",
       "legendFormat": "De-Dupe Ratio"
      }
     ]
    },
    {
     "title": "Chunk Size Bytes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"observatorium-loki-ingester-http\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Chunk Flush Reason %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(reason) (rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\" namespace=~\"$namespace\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\" namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Chunk Utilization",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{ job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{ namespace=\"$namespace\", pod=~\".*querier.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{ namespace=\"$namespace\", pod=~\".*querier.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Error Log Rate",
     "type": "graph",
     "gridPos": { "h": 3, "w": 18, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"} | logfmt |  level=\"error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 18, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"} |= \"level=error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"}[$__rate_interval])) by (route) > 0",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (method, name, le, container))",
       "legendFormat": "{{container}}: .99-{{method}}-{{name}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (method, name, le, container))",
       "legendFormat": "{{container}}: .9-{{method}}-{{name}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (method, name, le, container))",
       "legendFormat": "{{container}}: .5-{{method}}-{{name}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_memcache_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, method, name, container)",
       "legendFormat": "{{container}}: {{status_code}}-{{method}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_s3_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_s3_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_s3_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_s3_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BoltDB Shipper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_boltdb_shipper_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Loki / Overview",
 "tags": [
  "observatorium",
  "observatorium-logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memberlist Health Score",
   "type": "gauge",
   "description": "This metric describes a node's perception of its own health based on how well it is meeting the soft real-time requirements of the protocol. This metric ranges from 0 to 8, where 0 indicates \"totally healthy\". This health score is used to scale the time between outgoing probes, and higher scores translate into longer probing intervals. For more details see section IV of the Lifeguard paper: https://arxiv.org/pdf/1707.00788.pdf",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(loki_memberlist_client_cluster_node_health_score{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod\", \"observatorium.+(compactor.*|distributor.*|ingester.*|querier.*).*\")",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memberlist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CAS success rate",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  label_replace(rate(loki_memberlist_client_cas_success_total{namespace=\"$namespace\"}[5m]), \"pod\", \"$1\", \"pod\", \"observatorium.+(compactor.*|distributor.*|ingester.*|querier.*).*\")\n/\n  label_replace(rate(loki_memberlist_client_cas_attempt_total{namespace=\"$namespace\"}[5m]), \"pod\", \"$1\", \"pod\", \"observatorium.+(compactor.*|distributor.*|ingester.*|querier.*).*\")\n) \n> -1\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memberlist Members",
   "type": "stat",
   "description": "Every ingester, querier, distributor, compactor is expected to be a member of the memberlist. The actual members and expected members should be equal. ",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(pod)({namespace=\"$namespace\", pod=~\".+loki.+(compactor|ingester|querier|distributor|ruler).*\"}))",
     "legendFormat": "Expected Members"
    },
    {
     "expr": "bottomk(1, loki_memberlist_client_cluster_members_count{namespace=\"$namespace\"})",
     "legendFormat": "Actual Members"
    }
   ]
  },
  {
   "title": "Query Path",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Querier Success Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (route)(rate(loki_request_duration_seconds_count{namespace=\"$namespace\",job=~\".*loki-querier-http\", route=~\"loki_api_v1.*\", status_code!~\"5[0-9]{2}\"}[1m]))\n/\nsum by (route)(rate(loki_request_duration_seconds_count{namespace=\"$namespace\", job=~\".*loki-querier-http\", route=~\"loki_api_v1.*\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memcached Items in cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (memcached_current_items{namespace=\"$namespace\", job=~\"observatorium-loki.+\"}) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Memcached Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, command)(rate(memcached_commands_total{namespace=\"$namespace\", job=~\"observatorium-loki.+\"}[5m]))",
     "legendFormat": "{{job}} {{command}}"
    }
   ]
  },
  {
   "title": "Memcached evicts / reclaims",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(memcached_items_evicted_total{namespace=\"$namespace\", job=~\"observatorium-loki.+\"}[5m])) by(job)",
     "legendFormat": "{{job}} evicts"
    },
    {
     "expr": "sum(rate(memcached_items_reclaimed_total{namespace=\"$namespace\", job=~\"observatorium-loki.+\"}[5m])) by (job)",
     "legendFormat": "{{job}} reclaims"
    }
   ]
  },
  {
   "title": "Memcached Total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (memcached_current_bytes{namespace=\"$namespace\", job=~\"observatorium-loki.+\"}) / sum  by (job) (memcached_limit_bytes{namespace=\"$namespace\", job=~\"observatorium-loki.+\"})",
     "legendFormat": "{{job}} % used memory used"
    }
   ]
  },
  {
   "title": "Memcached % Hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (memcached_commands_total{status=\"miss\", namespace=\"$namespace\", job=~\"observatorium-loki.+\"})  / sum by (job)  (memcached_commands_total{namespace=\"$namespace\", job=~\"observatorium-loki.+\"}) ",
     "legendFormat": "{{job}} hit ratio"
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "S3 Latency by Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.95, sum(rate(loki_s3_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])) by (operation, le))"
      }
     ]
    },
    {
     "title": "S3 Status by Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status_code, operation)(rate(loki_s3_request_duration_seconds_count{namespace=\"$namespace\"}[5m])) "
      }
     ]
    }
   ]
  },
  {
   "title": "BoltDB Shipper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Shipper Status by Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code, operation)(rate(loki_boltdb_shipper_request_duration_seconds_count{namespace=\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Shipper Latency by Operation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{namespace=\"$namespace\"}[5m])) by (operation, le))"
    }
   ]
  },
  {
   "title": "Shipper Table Uploads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(loki_boltdb_shipper_tables_upload_operation_total{namespace=\"$namespace\"}[2m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Machine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(rate(process_cpu_seconds_total{namespace=\"$namespace\", pod=~\".+loki.+\"}[3m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(service)(process_resident_memory_bytes{namespace=\"$namespace\", pod=~\".+loki.+\"})",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "File Descriptors Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(service) (\n    process_open_fds{namespace=\"$namespace\", pod=~\".+loki.+\"}\n  /\n    process_max_fds{namespace=\"$namespace\", pod=~\".+loki.+\"}\n)",
     "legendFormat": "{{ service }}"
    }
   ]
  }
 ]
}