module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/itchyny/gojq v0.10.2 // cmd/gojq
	golang.org/x/sys v0.0.0-20220608164250-635b8c9b7f68 // indirect
)
