module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.14

require (
	github.com/fatih/color v1.10.0 // indirect
	github.com/google/go-jsonnet v0.16.0 // cmd/jsonnetfmt
	golang.org/x/sys v0.0.0-20201119102817-f84b799fce68 // indirect
)
