module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/google/go-jsonnet v0.18.0 // cmd/jsonnetfmt
	golang.org/x/sys v0.0.0-20220608164250-635b8c9b7f68 // indirect
)
