apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: loki-object-store-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app.kubernetes.io/name: ${SECRET_NAME}
    name: ${SECRET_NAME}
    namespace: ${NAMESPACE}
  stringData:
    access_key_id: ${ACCESS_KEY_ID}
    access_key_secret: ${SECRET_ACCESS_KEY}
    bucketnames: ${S3_BUCKET_NAME}
    endpoint: https://${S3_BUCKET_ENDPOINT}
    region: ${S3_BUCKET_REGION}
  type: Opaque
parameters:
- name: SECRET_NAME
  value: loki-default-bucket
- name: NAMESPACE
- name: S3_BUCKET_NAME
- name: S3_BUCKET_REGION
- name: S3_BUCKET_ENDPOINT
- name: ACCESS_KEY_ID
- name: SECRET_ACCESS_KEY
