apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: thanos-object-store-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: ${SECRET_NAME}
    name: ${SECRET_NAME}
    namespace: ${NAMESPACE}
  stringData:
    thanos.yaml: |-
      type: S3
      config:
        bucket: ${S3_BUCKET_NAME}
        region: ${S3_BUCKET_REGION}
        access_key: ${ACCESS_KEY_ID}
        secret_key: ${SECRET_ACCESS_KEY}
        endpoint: ${S3_BUCKET_ENDPOINT}
  type: Opaque
parameters:
- name: SECRET_NAME
- name: NAMESPACE
- name: S3_BUCKET_NAME
- name: S3_BUCKET_REGION
- name: S3_BUCKET_ENDPOINT
- name: ACCESS_KEY_ID
- name: SECRET_ACCESS_KEY
