{
 "title": "Loki Operational",
 "tags": [ "observatorium" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "logs", "query": "loki" },
   { "name": "metrics", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": "telemeter" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(loki_request_duration_seconds_count{  route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[5m]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pushes/Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n          rate(loki_request_duration_seconds_count{  route=~\"api_prom_push|loki_api_v1_push\"}[5m]),\n   \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Bad Words",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (name,level) (rate(promtail_custom_bad_words_total{ exported_namespace=\"$namespace\"}[$__interval])) - \nsum by (name,level) (rate(promtail_custom_bad_words_total{ exported_namespace=\"$namespace\"}[$__interval] offset 1h)))",
     "legendFormat": "{{name}}-{{level}}"
    }
   ]
  },
  {
   "title": "Lines Per Tenant (top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_lines_received_total{ namespace=\"$namespace\"}[5m])) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "MBs Per Tenant (Top 10)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_bytes_received_total{ namespace=\"$namespace\"}[5m])) by (tenant)) / 1024 / 1024",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{ namespace=\"$namespace\"}[10m]) > 0",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{ route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{ route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{ route=~\"api_prom_push|loki_api_v1_push\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-distributor-http\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-distributor-http\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-distributor-http\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\", status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", status_code!~\"5[0-9]{2}\", route=\"/logproto.Pusher/Push\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", route=\"/logproto.Pusher/Push\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}))",
     "legendFormat": "{{route}}-.5"
    }
   ]
  },
  {
   "title": "Querier Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-querier-http\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Querier Success Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\", status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (job_route:loki_request_duration_seconds_bucket:sum_rate{job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Read",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", status_code!~\"5[0-9]{2}\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label\"}[5m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discarded Lines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant, reason) (rate(loki_discarded_samples_total{namespace=\"$namespace\"}[1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    },
    {
     "title": "Discarded Lines Per Interval",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "topk(10, sum by (tenant, reason) (sum_over_time(increase(loki_discarded_samples_total{namespace=\"$namespace\"}[1m])[$__range:1m])))",
       "legendFormat": "{{ tenant }} - {{ reason }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{ namespace=\"$namespace\", pod=~\"distributor.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{ namespace=\"$namespace\", pod=~\"distributor.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"} |~ \"(?i)level=error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"} |~ \"(?i)level=error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\", status_code!~\"5[0-9]{2}\"}[5m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-distributor-http\"}[5m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Append Failures By Ingester",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_append_failures_total{ namespace=\"$namespace\"}[5m])) by (ingester)",
       "legendFormat": "{{ingester}}"
      }
     ]
    },
    {
     "title": "Bytes Received/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total{ namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Lines Received/Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total{ namespace=\"$namespace\"}[5m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{ namespace=\"$namespace\", pod=~\"ingester.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{ namespace=\"$namespace\", pod=~\"ingester.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\"} |~ \"(?i)level=error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\"} |~ \"(?i)level=error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\", status_code!~\"5[0-9]{2}\"}[1m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-ingester-http\"}[1m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Streams",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,sum by (tenant) (loki_ingester_memory_streams{job=\"observatorium-loki-ingester-http\"}))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Streams Created/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum by (tenant) (rate(loki_ingester_streams_created_total{job=\"observatorium-loki-ingester-http\"}[1m]) > 0))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunks Flushed/Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "Chunks"
      },
      {
       "expr": "sum(increase(cortex_chunk_store_deduped_chunks_total{ job=\"observatorium-loki-ingester-http\"}[1m]))/sum(increase(loki_ingester_chunks_flushed_total{ job=\"observatorium-loki-ingester-http\"}[1m])) < 1",
       "legendFormat": "De-Dupe Ratio"
      }
     ]
    },
    {
     "title": "Chunk Size Bytes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{job=\"observatorium-loki-ingester-http\"}[1m])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Chunk Flush Reason",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\",reason=\"full\"}[1m]))/sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "full"
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\",reason=\"synced\"}[1m]))/sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "synced"
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\",reason=\"idle\"}[1m]))/sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "idle"
      },
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\",reason=\"max_age\"}[1m]))/sum(rate(loki_ingester_chunks_flushed_total{job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "max_age"
      }
     ]
    },
    {
     "title": "Chunk Utilization",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{ job=\"observatorium-loki-ingester-http\"}[1m]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{ namespace=\"$namespace\", pod=~\"querier.*\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{ namespace=\"$namespace\", pod=~\"querier.*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate({ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"} |~ \"(?i)level=error\"[1m]))"
      }
     ]
    },
    {
     "title": "Logs",
     "type": "logs",
     "gridPos": { "h": 18, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"} |~ \"(?i)level=error\""
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\", status_code!~\"5[0-9]{2}\"}[1m])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{ namespace=\"$namespace\", job=\"observatorium-loki-querier-http\"}[1m])) by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memcached",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (method, name, le))",
       "legendFormat": ".99-{{method}}-{{name}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (method, name, le))",
       "legendFormat": ".9-{{method}}-{{name}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_memcache_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (method, name, le))",
       "legendFormat": ".5-{{method}}-{{name}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_memcache_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, method, name)",
       "legendFormat": "{{status_code}}-{{method}}-{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consul",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_consul_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_consul_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_consul_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_consul_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, status_code, method)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Big Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "MutateRows Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (operation, le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (operation, le))"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (operation, le))"
      }
     ]
    },
    {
     "title": "ReadRows Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (operation, le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (operation, le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (operation, le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "GetTable Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (operation, le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (operation, le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (operation, le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "ListTables Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (operation, le))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (operation, le))"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_bigtable_request_duration_seconds_bucket{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (operation, le))"
      }
     ]
    },
    {
     "title": "MutateRows Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_bigtable_request_duration_seconds_count{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/MutateRows\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "ReadRows Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_bigtable_request_duration_seconds_count{ namespace=\"$namespace\", operation=\"/google.bigtable.v2.Bigtable/ReadRows\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "GetTable Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_bigtable_request_duration_seconds_count{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/GetTable\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    },
    {
     "title": "ListTables Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_bigtable_request_duration_seconds_count{ namespace=\"$namespace\", operation=\"/google.bigtable.admin.v2.BigtableTableAdmin/ListTables\"}[5m])) by (status_code)",
       "legendFormat": "{{status_code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GCS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_gcs_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_gcs_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_gcs_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_gcs_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dynamo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failure Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_failures_total{ namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Consumed Capacity Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_consumed_capacity_total{ namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Throttled Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_throttled_total{ namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Dropped Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_dropped_requests_total{ namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Query Pages",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_dynamo_query_pages_count{ namespace=\"$namespace\"}[5m])))",
       "legendFormat": ".99"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_dynamo_query_pages_count{ namespace=\"$namespace\"}[5m])))",
       "legendFormat": ".9"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_dynamo_query_pages_count{ namespace=\"$namespace\"}[5m])))",
       "legendFormat": ".5"
      }
     ]
    },
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_dynamo_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_dynamo_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_dynamo_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_dynamo_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "S3",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_s3_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_s3_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_s3_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_s3_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cassandra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(cortex_cassandra_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(cortex_cassandra_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(cortex_cassandra_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cortex_cassandra_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BoltDB Shipper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".99-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.9, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".9-{{operation}}"
      },
      {
       "expr": "histogram_quantile(.5, sum(rate(loki_boltdb_shipper_request_duration_seconds_bucket{ namespace=\"$namespace\"}[5m])) by (operation, le))",
       "legendFormat": ".5-{{operation}}"
      }
     ]
    },
    {
     "title": "Status By Method",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(loki_boltdb_shipper_request_duration_seconds_count{ namespace=\"$namespace\"}[5m])) by (status_code, operation)",
       "legendFormat": "{{status_code}}-{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}