apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhobs-tools-logs
  labels:
    app: loki-operator
description: |
  This template deploys Loki via a LokiStack CR.
parameters:
  - name: NAMESPACE
    description: The namespace where Loki will be installed.
    required: true
    value: observatorium-tools
  - name: ACCESS_KEY_ID
  - name: SECRET_ACCESS_KEY
  - name: S3_BUCKET_NAME
  - name: S3_BUCKET_ENDPOINT
    value: s3.us-east-1.amazonaws.com
  - name: S3_BUCKET_REGION
    value: us-east-1
  - name: LOKI_SIZE
    description: The size of the Loki instance.
    required: true
    value: 1x.medium
  - name: LOKI_STORAGE_CLASS
    description: The storage class name to use for Loki.
    required: true
    value: gp2
  - name: LOKI_STORAGE_SECRET_NAME
    description: The Secret name to use for Loki storage
    required: true
    value: observatorium-loki
  - name: LOKI_STORAGE_SECRET_TYPE
    description: The storage type to use for Loki storage
    required: true
    value: s3
  - name: LOKI_TENANT_MODE
    description: The tenant mode to use for LokiStack
    required: true
    value: openshift-logging
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${LOKI_STORAGE_SECRET_NAME}
      namespace: ${NAMESPACE}
    type: Opaque
    stringData:
      access_key_id: ${ACCESS_KEY_ID}
      access_key_secret: ${SECRET_ACCESS_KEY}
      bucketnames: ${S3_BUCKET_NAME}
      endpoint: https://${S3_BUCKET_ENDPOINT}
      region: ${S3_BUCKET_REGION}
  - apiVersion: loki.grafana.com/v1
    kind: LokiStack
    metadata:
      name: observatorium-lokistack
      namespace: ${NAMESPACE}
    spec:
      managementState: Managed
      size: ${LOKI_SIZE}
      storage:
        schemas:
          - effectiveDate: '2022-06-01'
            version: v12
        secret:
          name: ${LOKI_STORAGE_SECRET_NAME}
          type: ${LOKI_STORAGE_SECRET_TYPE}
      storageClassName: ${LOKI_STORAGE_CLASS}
      tenants:
        mode: ${LOKI_TENANT_MODE}
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: rhobs-loki-logs-reader
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: rhobs-logcollector-lokistack-logs
    rules:
      - apiGroups:
          - 'loki.grafana.com'
        resources:
          - application
        resourceNames:
          - logs
        verbs:
          - 'create'
          - 'get'
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: rhobs-logcollector-lokistack-logs
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: rhobs-logcollector-lokistack-logs
    subjects:
      - kind: ServiceAccount
        name: logcollector
        namespace: openshift-logging
