apiVersion: v1
kind: Template
metadata:
  name: ${SECRET_NAME}
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${SECRET_NAME}
  stringData:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    issuer-url: https://sso.redhat.com/auth/realms/redhat-external
    tenants.yaml: ${TENANTS}
  type: Opaque
parameters:
- name: SECRET_NAME
- name: CLIENT_ID
- name: CLIENT_SECRET
- name: TENANTS
