apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: synthetics-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: ${IMAGE_TAG}
    name: synthetics-api
    namespace: ${NAMESPACE}
  spec:
    clusterIP: None
    ports:
    - name: synthetics-api
      port: 11211
      protocol: TCP
      targetPort: 11211
    selector:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: ${IMAGE_TAG}
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: ${IMAGE_TAG}
    name: synthetics-api
    namespace: ${NAMESPACE}
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: ${IMAGE_TAG}
    name: synthetics-api
    namespace: ${NAMESPACE}
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: synthetics-api
        app.kubernetes.io/instance: rhobs
        app.kubernetes.io/name: synthetics-api
        app.kubernetes.io/part-of: rhobs
        app.kubernetes.io/version: ${IMAGE_TAG}
    serviceName: synthetics-api
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: synthetics-api
          app.kubernetes.io/instance: rhobs
          app.kubernetes.io/name: synthetics-api
          app.kubernetes.io/part-of: rhobs
          app.kubernetes.io/version: ${IMAGE_TAG}
      spec:
        containers:
        - image: quay.io/redhat-services-prod/openshift/rhobs-synthetics-api:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: synthetics-api
          ports:
          - containerPort: 11211
            name: synthetics-api
            protocol: TCP
          resources: {}
          terminationMessagePolicy: FallbackToLogsOnError
        securityContext: {}
        serviceAccountName: synthetics-api
    updateStrategy: {}
  status:
    availableReplicas: 0
    replicas: 0
parameters:
- name: IMAGE_DIGEST
- name: IMAGE_TAG
  value: cea7d4656cd0ad338e580cc6ba266264a9938e5c
- name: NAMESPACE
  value: rhobs
