apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: observatorium-thanos-query-rule
objects:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      cert-manager.io/issuer-kind: ClusterIssuer
      cert-manager.io/issuer-name: letsencrypt-prod-http
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-query-rule
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
    name: observatorium-thanos-query-rule
    namespace: rhobs
  spec:
    host: ""
    port:
      targetPort: https
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: reencrypt
    to:
      kind: Service
      name: observatorium-thanos-query-rule
      weight: null
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-query-rule
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
    name: observatorium-thanos-query-rule
    namespace: rhobs
  spec:
    replicas: ${{QUERY_REPLICAS}}
    selector:
      matchLabels:
        app.kubernetes.io/component: query-layer
        app.kubernetes.io/instance: observatorium
        app.kubernetes.io/name: thanos-query-rule
        app.kubernetes.io/part-of: observatorium
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: query-layer
          app.kubernetes.io/instance: observatorium
          app.kubernetes.io/name: thanos-query-rule
          app.kubernetes.io/part-of: observatorium
          app.kubernetes.io/version: v0.32.5
        namespace: rhobs
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - observatorium
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - thanos-query-rule
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - args:
          - query
          - --endpoint=dnssrv+_grpc._tcp.observatorium-thanos-receive-ingestor-default.rhobs.svc.cluster.local
          - --endpoint=dnssrv+_grpc._tcp.observatorium-thanos-receive-ingestor-rhel.rhobs.svc.cluster.local
          - --endpoint=dnssrv+_grpc._tcp.observatorium-thanos-receive-ingestor-telemeter.rhobs.svc.cluster.local
          - --endpoint=dnssrv+_grpc._tcp.observatorium-thanos-store-default.rhobs.svc.cluster.local
          - --endpoint=dnssrv+_grpc._tcp.observatorium-thanos-store-rhel.rhobs.svc.cluster.local
          - --endpoint=dnssrv+_grpc._tcp.observatorium-thanos-store-telemeter.rhobs.svc.cluster.local
          - --endpoint=http://observatorium-thanos-rule-default.rhobs.svc.cluster.local:10902
          - --endpoint=http://observatorium-thanos-rule-rhel.rhobs.svc.cluster.local:10902
          - --endpoint=http://observatorium-thanos-rule-telemeter.rhobs.svc.cluster.local:10902
          - --log.format=logfmt
          - --log.level=${QUERY_LOG_LEVEL}
          - --query.auto-downsampling
          - --query.lookback-delta=15m0s
          - --query.max-concurrent=10
          - --query.promql-engine=prometheus
          - --query.replica-label=replica
          - --query.replica-label=prometheus_replica
          - --query.replica-label=rule_replica
          - --query.timeout=15m0s
          - |
            --tracing.config=type: JAEGER
            config:
              service_name: thanos-query-rule
              sampler_type: ratelimiting
              sampler_param: 2
          - --web.prefix-header=X-Forwarded-Prefix
          env:
          - name: HOST_IP_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          image: quay.io/thanos/thanos:v0.32.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /-/healthy
              port: 10902
            periodSeconds: 30
            timeoutSeconds: 1
          name: thanos
          ports:
          - containerPort: 10902
            name: http
            protocol: TCP
          - containerPort: 10901
            name: grpc
            protocol: TCP
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /-/ready
              port: 10902
            periodSeconds: 5
          resources:
            limits:
              memory: ${QUERY_MEMORY_LIMIT}
            requests:
              cpu: ${QUERY_CPU_REQUEST}
              memory: ${QUERY_MEMORY_REQUEST}
          terminationMessagePolicy: FallbackToLogsOnError
        - args:
          - --reporter.grpc.host-port=dns:///otel-trace-writer-collector-headless.observatorium-tools.svc:14250
          - --reporter.type=grpc
          - --agent.tags=pod.namespace=$(NAMESPACE),pod.name=$(POD)
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: quay.io/app-sre/jaegertracing-jaeger-agent:1.22.0
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 14271
          name: jaeger-agent
          ports:
          - containerPort: 5778
            name: configs
            protocol: TCP
          - containerPort: 6831
            name: jaeger-thrift
            protocol: TCP
          - containerPort: 14271
            name: metrics
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 14271
            initialDelaySeconds: 1
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 32m
              memory: 64Mi
          terminationMessagePolicy: FallbackToLogsOnError
        - args:
          - -provider=openshift
          - -https-address=:8443
          - -http-address=
          - -email-domain=*
          - -upstream=http://localhost:10902
          - -openshift-service-account=observatorium-thanos-query-rule
          - '-openshift-sar={"resource": "namespaces", "verb": "get", "name": "rhobs",
            "namespace": "rhobs"}'
          - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get",
            "name": "rhobs", "namespace": "rhobs"}}'
          - -tls-cert=/etc/tls/private/tls.crt
          - -tls-key=/etc/tls/private/tls.key
          - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
          - -cookie-secret=${OAUTH_PROXY_COOKIE_SECRET}
          - -openshift-ca=/etc/pki/tls/cert.pem
          - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          image: quay.io/openshift/origin-oauth-proxy:4.15
          name: oauth-proxy
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
          - mountPath: /etc/tls/private
            name: tls
            readOnly: true
        nodeSelector:
          kubernetes.io/os: linux
        serviceAccountName: observatorium-thanos-query-rule
        terminationGracePeriodSeconds: 120
        volumes:
        - name: tls
          secret:
            secretName: query-rule-tls
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: query-rule-tls
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-query-rule
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
    name: observatorium-thanos-query-rule
    namespace: rhobs
  spec:
    ports:
    - name: http
      port: 10902
      protocol: TCP
      targetPort: 10902
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: 10901
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-query-rule
      app.kubernetes.io/part-of: observatorium
- apiVersion: v1
  imagePullSecrets:
  - name: quay.io
  kind: ServiceAccount
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.application: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"observatorium-thanos-query-rule"}}'
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-query-rule
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
    name: observatorium-thanos-query-rule
    namespace: rhobs
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-query-rule
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
      prometheus: app-sre
    name: observatorium-thanos-query-rule
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - port: http
      relabelings:
      - action: replace
        separator: /
        sourceLabels:
        - namespace
        - pod
        targetLabel: instance
    namespaceSelector:
      matchNames:
      - rhobs
    selector:
      matchLabels:
        app.kubernetes.io/component: query-layer
        app.kubernetes.io/instance: observatorium
        app.kubernetes.io/name: thanos-query-rule
        app.kubernetes.io/part-of: observatorium
parameters:
- from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: OAUTH_PROXY_COOKIE_SECRET
- name: QUERY_CPU_REQUEST
  value: 250m
- name: QUERY_LOG_LEVEL
  value: warn
- name: QUERY_MEMORY_LIMIT
  value: 8Gi
- name: QUERY_MEMORY_REQUEST
  value: 2Gi
- name: QUERY_REPLICAS
  value: "1"
