apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: synthetics-api
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: 7b1c37783b4937b44ab878752df8390d5b9b0b1989e7a49e28f7c33ff9aee910
    name: synthetics-api
    namespace: rhobs-int
  spec:
    clusterIP: None
    ports:
    - name: synthetics-api
      port: 11211
      protocol: TCP
      targetPort: 11211
    selector:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: 7b1c37783b4937b44ab878752df8390d5b9b0b1989e7a49e28f7c33ff9aee910
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: 7b1c37783b4937b44ab878752df8390d5b9b0b1989e7a49e28f7c33ff9aee910
    name: synthetics-api
    namespace: rhobs-int
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: synthetics-api
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: synthetics-api
      app.kubernetes.io/part-of: rhobs
      app.kubernetes.io/version: 7b1c37783b4937b44ab878752df8390d5b9b0b1989e7a49e28f7c33ff9aee910
    name: synthetics-api
    namespace: rhobs-int
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: synthetics-api
        app.kubernetes.io/instance: rhobs
        app.kubernetes.io/name: synthetics-api
        app.kubernetes.io/part-of: rhobs
        app.kubernetes.io/version: 7b1c37783b4937b44ab878752df8390d5b9b0b1989e7a49e28f7c33ff9aee910
    serviceName: synthetics-api
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: synthetics-api
          app.kubernetes.io/instance: rhobs
          app.kubernetes.io/name: synthetics-api
          app.kubernetes.io/part-of: rhobs
          app.kubernetes.io/version: 7b1c37783b4937b44ab878752df8390d5b9b0b1989e7a49e28f7c33ff9aee910
      spec:
        containers:
        - image: quay.io/redhat-user-workloads/rhobs-synthetics-tenant/rhobs-synthetics-api-main/rhobs-synthetics-api-main:7b1c37783b4937b44ab878752df8390d5b9b0b1989e7a49e28f7c33ff9aee910
          imagePullPolicy: IfNotPresent
          name: synthetics-api
          ports:
          - containerPort: 11211
            name: synthetics-api
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePolicy: FallbackToLogsOnError
        securityContext: {}
        serviceAccountName: synthetics-api
    updateStrategy: {}
  status:
    availableReplicas: 0
    replicas: 0
