apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: thanos-default-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/name: observatorium-mst-thanos-objectstorage
    name: observatorium-mst-thanos-objectstorage
    namespace: rhobs-production
  stringData:
    thanos.yaml: |-
      type: S3
      config:
        bucket: ${S3_BUCKET_NAME}
        region: ${S3_BUCKET_REGION}
        access_key: ${ACCESS_KEY_ID}
        secret_key: ${SECRET_ACCESS_KEY}
        endpoint: ${S3_BUCKET_ENDPOINT}
  type: Opaque
parameters:
- name: S3_BUCKET_NAME
- name: S3_BUCKET_REGION
- name: S3_BUCKET_ENDPOINT
- name: ACCESS_KEY_ID
- name: SECRET_ACCESS_KEY
