apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: observatorium-thanos-receive-ingestor-rhel
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: database-write-hashring-ingestor
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-receive-ingestor
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
      observatorium/tenant: rhel
    name: observatorium-thanos-receive-ingestor-rhel
    namespace: rhobs
  spec:
    ports:
    - name: http
      port: 10902
      protocol: TCP
      targetPort: 10902
    - name: grpc
      port: 10901
      protocol: TCP
      targetPort: 10901
    - name: remote-write
      port: 19291
      protocol: TCP
      targetPort: 19291
    selector:
      app.kubernetes.io/component: database-write-hashring-ingestor
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-receive-ingestor
      app.kubernetes.io/part-of: observatorium
      observatorium/tenant: rhel
- apiVersion: v1
  imagePullSecrets:
  - name: quay.io
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: database-write-hashring-ingestor
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-receive-ingestor
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
      observatorium/tenant: rhel
    name: observatorium-thanos-receive-ingestor-rhel
    namespace: rhobs
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: database-write-hashring-ingestor
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-receive-ingestor
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
      observatorium/tenant: rhel
      prometheus: app-sre
    name: observatorium-thanos-receive-ingestor-rhel
    namespace: openshift-customer-monitoring
  spec:
    endpoints:
    - port: http
      relabelings:
      - action: replace
        separator: /
        sourceLabels:
        - namespace
        - pod
        targetLabel: instance
    namespaceSelector:
      matchNames:
      - rhobs
    selector:
      matchLabels:
        app.kubernetes.io/component: database-write-hashring-ingestor
        app.kubernetes.io/instance: observatorium
        app.kubernetes.io/name: thanos-receive-ingestor
        app.kubernetes.io/part-of: observatorium
        observatorium/tenant: rhel
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: database-write-hashring-ingestor
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-receive-ingestor
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: v0.32.5
      controller.receive.thanos.io: thanos-receive-controller
      controller.receive.thanos.io/hashring: rhel
      observatorium/tenant: rhel
    name: observatorium-thanos-receive-ingestor-rhel
    namespace: rhobs
  spec:
    replicas: ${{INGESTOR_REPLICAS}}
    selector:
      matchLabels:
        app.kubernetes.io/component: database-write-hashring-ingestor
        app.kubernetes.io/instance: observatorium
        app.kubernetes.io/name: thanos-receive-ingestor
        app.kubernetes.io/part-of: observatorium
        observatorium/tenant: rhel
    serviceName: observatorium-thanos-receive-ingestor-rhel
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: database-write-hashring-ingestor
          app.kubernetes.io/instance: observatorium
          app.kubernetes.io/name: thanos-receive-ingestor
          app.kubernetes.io/part-of: observatorium
          app.kubernetes.io/version: v0.32.5
          observatorium/tenant: rhel
        namespace: rhobs
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                    - observatorium
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - thanos-receive-ingestor
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - args:
          - receive
          - --grpc-address=0.0.0.0:10901
          - --http-address=0.0.0.0:10902
          - --label=replica="$(POD_NAME)"
          - --log.format=logfmt
          - --log.level=${INGESTOR_LOG_LEVEL}
          - --objstore.config=$(OBJSTORE_CONFIG)
          - --remote-write.address=0.0.0.0:19291
          - |
            --tracing.config=type: JAEGER
            config:
              service_name: thanos-receive-ingestor-rhel
              sampler_type: ratelimiting
              sampler_param: 2
          - --tsdb.path=/var/thanos/receive
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: aws_access_key_id
                name: rhelemeter-tenant-s3
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: aws_secret_access_key
                name: rhelemeter-tenant-s3
          - name: OBJ_STORE_BUCKET
            valueFrom:
              secretKeyRef:
                key: bucket
                name: rhelemeter-tenant-s3
          - name: OBJ_STORE_REGION
            valueFrom:
              secretKeyRef:
                key: aws_region
                name: rhelemeter-tenant-s3
          - name: OBJ_STORE_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: endpoint
                name: rhelemeter-tenant-s3
          - name: OBJSTORE_CONFIG
            value: |
              type: S3
              config:
                  bucket: $(OBJ_STORE_BUCKET)
                  endpoint: $(OBJ_STORE_ENDPOINT)
                  region: $(OBJ_STORE_REGION)
          image: quay.io/thanos/thanos:v0.32.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /-/healthy
              port: 10902
            periodSeconds: 30
            timeoutSeconds: 1
          name: thanos
          ports:
          - containerPort: 10902
            name: http
            protocol: TCP
          - containerPort: 10901
            name: grpc
            protocol: TCP
          - containerPort: 19291
            name: remote-write
            protocol: TCP
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /-/ready
              port: 10902
            initialDelaySeconds: 60
            periodSeconds: 5
          resources:
            limits:
              memory: ${INGESTOR_MEMORY_LIMIT}
            requests:
              cpu: ${INGESTOR_CPU_REQUEST}
              memory: ${INGESTOR_MEMORY_REQUEST}
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
          - mountPath: /var/thanos/receive
            name: data
        - args:
          - --reporter.grpc.host-port=dns:///otel-trace-writer-collector-headless.observatorium-tools.svc:14250
          - --reporter.type=grpc
          - --agent.tags=pod.namespace=$(NAMESPACE),pod.name=$(POD)
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: quay.io/app-sre/jaegertracing-jaeger-agent:1.22.0
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: 14271
          name: jaeger-agent
          ports:
          - containerPort: 5778
            name: configs
            protocol: TCP
          - containerPort: 6831
            name: jaeger-thrift
            protocol: TCP
          - containerPort: 14271
            name: metrics
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 14271
            initialDelaySeconds: 1
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 32m
              memory: 64Mi
          terminationMessagePolicy: FallbackToLogsOnError
        nodeSelector:
          kubernetes.io/os: linux
        serviceAccountName: observatorium-thanos-receive-ingestor-rhel
        terminationGracePeriodSeconds: 120
    updateStrategy: {}
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: database-write-hashring-ingestor
          app.kubernetes.io/instance: observatorium
          app.kubernetes.io/name: thanos-receive-ingestor
          app.kubernetes.io/part-of: observatorium
          app.kubernetes.io/version: v0.32.5
          observatorium/tenant: rhel
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: gp2
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: database-write-hashring-ingestor
      app.kubernetes.io/instance: observatorium
      app.kubernetes.io/name: thanos-receive-ingestor
      app.kubernetes.io/part-of: observatorium
      controller.receive.thanos.io: thanos-receive-controller
      controller.receive.thanos.io/hashring: rhel
      observatorium/tenant: rhel
    name: observatorium-thanos-receive-ingestor-rhel
    namespace: rhobs
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: database-write-hashring-ingestor
        app.kubernetes.io/instance: observatorium
        app.kubernetes.io/name: thanos-receive-ingestor
        app.kubernetes.io/part-of: observatorium
        controller.receive.thanos.io: thanos-receive-controller
        controller.receive.thanos.io/hashring: rhel
        observatorium/tenant: rhel
parameters:
- name: INGESTOR_CPU_REQUEST
  value: 200m
- name: INGESTOR_LOG_LEVEL
  value: warn
- name: INGESTOR_MEMORY_LIMIT
  value: 10Gi
- name: INGESTOR_MEMORY_REQUEST
  value: 3Gi
- name: INGESTOR_REPLICAS
  value: "1"
