{
 "title": "OpenTelemetry Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "exporter", "label": "exporter", "query": "label_values(otelsvc_exporter)" },
   { "name": "processor", "label": "processor", "query": "label_values(processor)" }
  ]
 },
 "panels": [
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spans Accepted vs Refused /Second",
   "type": "graph",
   "description": "Rate of spans successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{namespace=\"observatorium-traces\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} spans accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{namespace=\"observatorium-traces\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} spans refused /sec"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Spans Exported vs Failed / Second",
   "type": "graph",
   "description": "Rate of spans successfully exported vs Failed per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{namespace=\"observatorium-traces\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{namespace=\"observatorium-traces\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} failed /sec"
    }
   ]
  },
  {
   "title": "Queued Retry Max Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_size)",
     "legendFormat": "Queue Size"
    }
   ]
  },
  {
   "title": "Queued Retry Max Queue Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_capacity{namespace=\"observatorium-traces\"})",
     "legendFormat": "Queue Capacity"
    }
   ]
  },
  {
   "title": "Queued Failed Sent/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_enqueue_failed_spans{namespace=\"observatorium-traces\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Processor Spans Received, Dropped, Accepted, Refused/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otelcol_processor_dropped_spans{namespace=\"observatorium-traces\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | received"
    },
    {
     "expr": "sum(rate(otelcol_processor_accepted_spans{namespace=\"observatorium-traces\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | accepted"
    },
    {
     "expr": "sum(rate(otelcol_processor_refused_spans{namespace=\"observatorium-traces\"}[1m])) by (processor)",
     "legendFormat": "{{processor}} | refused"
    }
   ]
  }
 ]
}