{
 "title": "Query Frontend Overview",
 "panels": [
  {
   "title": "Rate of requests",
   "type": "graph",
   "description": "Shows rate of requests against Query Frontend for the given time.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\", handler=\"query-frontend\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Rate of queries",
   "type": "graph",
   "description": "Shows rate of queries passing through Query Frontend",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(thanos_query_frontend_queries_total{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\", op=\"query_range\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against Query Frontend.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\", handler=\"query-frontend\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\", handler=\"query-frontend\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\"}",
     "legendFormat": "alloc all {{instance}}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\"}",
     "legendFormat": "alloc heap {{instance}}"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\"}[30s])",
     "legendFormat": "alloc rate all {{instance}}"
    },
    {
     "expr": "rate(go_memstats_heap_alloc_bytes{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\"}[30s])",
     "legendFormat": "alloc rate heap {{instance}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\"}",
     "legendFormat": "inuse heap {{instance}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", job=~\"observatorium-thanos-query-frontend\"}",
     "legendFormat": "inuse stack {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"observatorium-thanos-query-frontend\", namespace=\"$namespace\"}[5m]) * 100",
     "legendFormat": "cpu usage system {{instance}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\", container='thanos-query-frontend'}",
     "legendFormat": "pod {{pod}}"
    }
   ]
  }
 ]
}