{
 "title": "MST Stage SLOs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 15 },
   "options": {
    "content": "This dashboard displays the SLOs as defined in the [RHOBS Service Level Objectives](https://docs.google.com/document/d/1wJjcpgg-r8rlnOtRiqWGv0zwr1MB6WwkQED1XDWXVQs/edit) document."
   }
  },
  {
   "title": "API > Metrics Write > Availability",
   "type": "row"
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of valid requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"receive\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"receive\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"receive\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"receive\",code!~\"4.+\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  { "title": "API > Metrics Write > Latency", "type": "row" },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests return < 5s</center>"
   }
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile( 0.90000000000000002, sum by (le) ( rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"receive\"}[28d]) ))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    (\n        (\n            sum(rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"receive\",le=\"5\"}[28d]))\n            /\n            sum(rate(http_request_duration_seconds_count{job=\"observatorium-observatorium-mst-api\",code!~\"4..\",group=\"metricsv1\",handler=~\"receive\"}[28d]))\n        ) - 0.90000000000000002\n    )\n    /\n    (1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  {
   "title": "API > Metrics Read > Availability",
   "type": "row"
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of valid /query requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=\"query\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=\"query\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=\"query\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=\"query\",code!~\"4.+\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of valid /query_range requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"query_range\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"query_range\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"query_range\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"query_range\",code!~\"4.+\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  { "title": "API > Metrics Read > Latency", "type": "row" },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests that process 1M samples return < 10s</center>"
   }
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile( 0.90000000000000002, sum by (le) ( rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-1M-samples\"}[1d]) ))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    (\n        (\n            sum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-1M-samples\",le=\"10\"}[28d]))\n            /\n            sum(rate(up_custom_query_duration_seconds_count{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-1M-samples\"}[28d]))\n        ) - 0.90000000000000002\n    )\n    /\n    (1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests that process 10M samples return < 30s</center>"
   }
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile( 0.90000000000000002, sum by (le) ( rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-10M-samples\"}[1d]) ))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    (\n        (\n            sum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-10M-samples\",le=\"30\"}[28d]))\n            /\n            sum(rate(up_custom_query_duration_seconds_count{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-10M-samples\"}[28d]))\n        ) - 0.90000000000000002\n    )\n    /\n    (1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests that process 100M samples return < 120s</center>"
   }
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile( 0.90000000000000002, sum by (le) ( rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-100M-samples\"}[1d]) ))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    (\n        (\n            sum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-100M-samples\",le=\"120\"}[28d]))\n            /\n            sum(rate(up_custom_query_duration_seconds_count{namespace=\"observatorium-mst-stage\",query=\"query-path-sli-100M-samples\"}[28d]))\n        ) - 0.90000000000000002\n    )\n    /\n    (1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  {
   "title": "API > Rules Write (/rules/raw) > Availability",
   "type": "row"
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of valid write requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code=~\"5.+\",method=~\"PUT\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code!~\"4.+\",method=~\"PUT\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code=~\"5.+\",method=~\"PUT\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code!~\"4.+\",method=~\"PUT\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  {
   "title": "API > Rules Sync > Availability",
   "type": "row"
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of rules are successfully synced to Thanos Ruler</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(client_api_requests_total{client=\"oauth\",container=\"thanos-rule-syncer\",namespace=\"observatorium-mst-stage\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(client_api_requests_total{client=\"oauth\",container=\"thanos-rule-syncer\",namespace=\"observatorium-mst-stage\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(client_api_requests_total{client=\"oauth\",container=\"thanos-rule-syncer\",namespace=\"observatorium-mst-stage\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(client_api_requests_total{client=\"oauth\",container=\"thanos-rule-syncer\",namespace=\"observatorium-mst-stage\",code!~\"4.+\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  {
   "title": "API > Rules Read (/rules) > Availability",
   "type": "row"
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules\",code!~\"4.+\"}[28d]))\n    ) - 0.90000000000000002\n)\n/\n(1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  {
   "title": "API > Rules Read (/rules/raw) > Availability",
   "type": "row"
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"metricsv1\",handler=~\"rules-raw\",code!~\"4.+\"}[28d]))\n    ) - 0.90000000000000002\n)\n/\n(1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  { "title": "API > Alerting > Availability", "type": "row" },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of alerts are successfully delivered to Alertmanager</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(thanos_alert_sender_alerts_dropped_total{container=\"thanos-rule\",namespace=\"observatorium-mst-stage\"}[28d])) or vector(0))\n/\nsum(rate(thanos_alert_sender_alerts_sent_total{container=\"thanos-rule\",namespace=\"observatorium-mst-stage\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(thanos_alert_sender_alerts_dropped_total{container=\"thanos-rule\",namespace=\"observatorium-mst-stage\"}[28d])) or vector(0))\n        /\n        sum(rate(thanos_alert_sender_alerts_sent_total{container=\"thanos-rule\",namespace=\"observatorium-mst-stage\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of alerts are successfully delivered to upstream targets</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(alertmanager_notifications_failed_total{service=\"observatorium-alertmanager\",namespace=\"observatorium-mst-stage\"}[28d])) or vector(0))\n/\nsum(rate(alertmanager_notifications_total{service=\"observatorium-alertmanager\",namespace=\"observatorium-mst-stage\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(alertmanager_notifications_failed_total{service=\"observatorium-alertmanager\",namespace=\"observatorium-mst-stage\"}[28d])) or vector(0))\n        /\n        sum(rate(alertmanager_notifications_total{service=\"observatorium-alertmanager\",namespace=\"observatorium-mst-stage\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  {
   "title": "API > Logs Write > Availability",
   "type": "row"
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of valid requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"push\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"push\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"push\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"push\",code!~\"4.+\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  { "title": "API > Logs Write > Latency", "type": "row" },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">90% of valid requests return < 5s</center>"
   }
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile( 0.90000000000000002, sum by (le) ( rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",code!~\"4..\",group=\"logsv1\",handler=~\"push\"}[28d]) ))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n    (\n        (\n            sum(rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-mst-api\",code!~\"4..\",group=\"logsv1\",handler=~\"push\",le=\"5\"}[28d]))\n            /\n            sum(rate(http_request_duration_seconds_count{job=\"observatorium-observatorium-mst-api\",code!~\"4..\",group=\"logsv1\",handler=~\"push\"}[28d]))\n        ) - 0.90000000000000002\n    )\n    /\n    (1 - 0.90000000000000002), 0)\n"
    }
   ]
  },
  { "title": "API > Logs Read > Availability", "type": "row" },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of valid /query requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=\"query\",code!~\"4.+\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">95% of valid /query_range requests return successfully</center>"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-\n(sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query_range\",code=~\"5.+\"}[28d])) or vector(0))\n/\nsum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query_range\",code!~\"4.+\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 -\n    (\n        (sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query_range\",code=~\"5.+\"}[28d])) or vector(0))\n        /\n        sum(rate(http_requests_total{job=\"observatorium-observatorium-mst-api\",group=\"logsv1\",handler=~\"query_range\",code!~\"4.+\"}[28d]))\n    ) - 0.94999999999999996\n)\n/\n(1 - 0.94999999999999996), 0)\n"
    }
   ]
  }
 ]
}