{
 "title": "SLOs - Telemeter - Staging",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Description",
   "type": "text",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard displays the SLOs as defined in the [RHOBS Service Level Objectives](https://docs.google.com/document/d/1wJjcpgg-r8rlnOtRiqWGv0zwr1MB6WwkQED1XDWXVQs/edit) document."
   }
  },
  {
   "title": "Telemeter Server > Metrics Write > Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n95% of valid requests return successfully\n\n</center>\n\n"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- sum(rate(haproxy_server_http_responses_total{route=~\"telemeter-server-upload|telemeter-server-metrics-v1-receive\",code=\"5xx\"}[28d]))\n/\nsum(rate(haproxy_server_http_responses_total{route=~\"telemeter-server-upload|telemeter-server-metrics-v1-receive\", code!=\"4xx\"}[28d]))\n\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    1 -\n    sum(rate(haproxy_server_http_responses_total{route=~\"telemeter-server-upload|telemeter-server-metrics-v1-receive\",code=\"5xx\"}[28d]))\n    /\n    sum(rate(haproxy_server_http_responses_total{route=~\"telemeter-server-upload|telemeter-server-metrics-v1-receive\", code!=\"4xx\"}[28d]))\n  ) - 0.95\n)\n/ \n(1 - 0.95), 0)"
    }
   ]
  },
  {
   "title": "Telemeter Server > Metrics Write > Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n90% of valid requests return < 5s\n\n</center>\n\n"
   }
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"4..\",handler=~\"upload|receive\"}[28d])))"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    sum(rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",handler=~\"upload|receive\",le=\"5\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{job=\"telemeter-server\",handler=~\"upload|receive\"}[28d]))\n  ) - 0.9\n)\n/ \n(1 - 0.9), 0)"
    }
   ]
  },
  {
   "title": "API > Metrics Write > Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n95% of valid requests return successfully\n\n</center>\n\n"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\n(\n  sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"receive\", code=~\"5.+\"}[28d])) or vector(0)\n  /\n  sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"receive\", code!~\"4.+\"}[28d]))\n)"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n( 1 - \n  (\n     sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"receive\", code=~\"5.+\"}[28d])) or vector(0)\n    /\n    sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"receive\", code!~\"4.+\"}[28d]))\n  ) - 0.95\n)\n/ \n(1 - 0.95), 0)"
    }
   ]
  },
  { "title": "API > Metrics Write > Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 22 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n90% of valid requests return < 5s\n\n</center>\n\n"
   }
  },
  {
   "title": "90th Percentile Request Latency (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-api\",code!~\"4..\",handler=~\"receive\"}[28d])))"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    sum(rate(http_request_duration_seconds_bucket{job=\"observatorium-observatorium-api\",code!~\"4..\",handler=~\"receive\", le=\"5\"}[28d]))\n/\nsum(rate(http_request_duration_seconds_count{job=\"observatorium-observatorium-api\",code!~\"4..\",handler=~\"receive\"}[28d]))\n  ) - 0.9\n)\n/ \n(1 - 0.9), 0)"
    }
   ]
  },
  {
   "title": "API > Metrics Read > Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 28 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n95% of valid /query requests return successfully\n\n</center>\n\n"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\n(\n  sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=\"query\", code=~\"5.+\"}[28d]))\n  /\n  sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=\"query\", code!~\"4.+\"}[28d]))\n)"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    1 -\n     sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=\"query\", code=~\"5.+\"}[28d]))\n    /\n    sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=\"query\", code!~\"4.+\"}[28d]))\n  ) - 0.95\n)\n/ \n(1 - 0.95), 0)"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 33 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n95% of valid /query_range requests return successfully\n\n</center>\n\n"
   }
  },
  {
   "title": "Availability (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 -\n(\n  sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"query_range\", code=~\"5.+\"}[28d]))\n  /\n  sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"query_range\", code!~\"4.+\"}[28d]))\n)"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    1 -\n     sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"query_range\", code=~\"5.+\"}[28d]))\n    /\n    sum(rate(http_requests_total{job=\"observatorium-observatorium-api\",handler=~\"query_range\", code!~\"4.+\"}[28d]))\n  ) - 0.95\n)\n/ \n(1 - 0.95), 0)"
    }
   ]
  },
  { "title": "API > Metrics Read > Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 39 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n90% of valid requests that process 1M samples return < 2s\n\n</center>\n\n"
   }
  },
  {
   "title": "90th Percentile Request Latency (1d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-1M-samples\"}[1d])))"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    sum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-1M-samples\",le=\"2.0113571874999994\"}[28d]))\n/\nsum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-1M-samples\"}[28d]))\n  ) - 0.9\n)\n/ \n(1 - 0.9), 0)"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 44 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n90% of valid requests that process 10M samples return < 10s\n\n</center>\n\n"
   }
  },
  {
   "title": "90th Percentile Request Latency (1d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-10M-samples\"}[1d])))"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    sum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-10M-samples\",le=\"10.761264004567169\"}[28d]))\n/\nsum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-10M-samples\"}[28d]))\n  ) - 0.9\n)\n/ \n(1 - 0.9), 0)"
    }
   ]
  },
  {
   "title": "SLO",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 49 },
   "options": {
    "content": "<center style=\"font-size: 25px;\">\n\n90% of valid requests that process 100M samples return < 20s\n\n</center>\n\n"
   }
  },
  {
   "title": "90th Percentile Request Latency (1d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-100M-samples\"}[1d])))"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n(\n  (\n    sum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-100M-samples\",le=\"21.6447457021712\"}[28d]))\n/\nsum(rate(up_custom_query_duration_seconds_bucket{namespace=\"observatorium-stage\",query=\"query-path-sli-100M-samples\"}[28d]))\n  ) - 0.9\n)\n/ \n(1 - 0.9), 0)"
    }
   ]
  }
 ]
}