{
 "title": "Telemeter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "interval",
    "label": "Rate Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Telemeter v1 (/authorize & /upload)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Availability (28d)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_server_http_responses_total{route=~\"telemeter-server-authorize|telemeter-server-upload\",code=\"5xx\"}[28d]))\n/\nsum(increase(haproxy_server_http_responses_total{route=~\"telemeter-server-authorize|telemeter-server-upload\"}[28d]))\n"
    }
   ]
  },
  {
   "title": "Error Budget (28d)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (\n    1 -\n    sum(increase(haproxy_server_http_responses_total{route=~\"telemeter-server-authorize|telemeter-server-upload\",code=\"5xx\"}[28d]))\n    /\n    sum(increase(haproxy_server_http_responses_total{route=~\"telemeter-server-authorize|telemeter-server-upload\"}[28d]))\n  ) - 0.98\n)\n/ \n(1 - 0.98)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "/authorize", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Availability (selected time range)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_server_http_responses_total{route=\"telemeter-server-authorize\",code=\"5xx\"}[$__range]))\n/\nsum(increase(haproxy_server_http_responses_total{route=\"telemeter-server-authorize\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 10 },
   "repeat": "handler",
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_server_http_responses_total{route=\"telemeter-server-authorize\"}[$interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_server_http_responses_total{route=\"telemeter-server-authorize\",code=\"5xx\"}[$interval])) / sum(rate(haproxy_server_http_responses_total{route=\"telemeter-server-authorize\"}[$interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"authorize\"}[$interval])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"authorize\"}[$interval])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"authorize\"}[$interval])))",
     "legendFormat": "50th"
    }
   ]
  },
  { "title": "/upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Availability (selected time range)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 20 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 -\nsum(increase(haproxy_server_http_responses_total{route=~\"telemeter-server-authorize|telemeter-server-upload\",code=\"5xx\"}[$__range]))\n/\nsum(increase(haproxy_server_http_responses_total{route=~\"telemeter-server-authorize|telemeter-server-upload\"}[$__range]))\n"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(haproxy_server_http_responses_total{route=\"telemeter-server-upload\"}[$interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(haproxy_server_http_responses_total{route=\"telemeter-server-upload\",code=\"5xx\"}[$interval])) / sum(rate(haproxy_server_http_responses_total{route=\"telemeter-server-upload\"}[$interval]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"upload\"}[$interval])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"upload\"}[$interval])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"upload\"}[$interval])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "/receive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability (selected time range)",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 30 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "1 - \nsum(increase(haproxy_server_http_responses_total{route=\"telemeter-server-metrics-v1-receive\",code=\"5xx\"}[$__range]))\n/\nsum(increase(haproxy_server_http_responses_total{route=\"telemeter-server-metrics-v1-receive\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 3, "y": 30 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(haproxy_server_http_responses_total{route=\"telemeter-server-metrics-v1-receive\"}[$interval]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 10, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (code) (rate(haproxy_server_http_responses_total{route=\"telemeter-server-metrics-v1-receive\",code=\"5xx\"}[$interval])) / sum by (code) (rate(haproxy_server_http_responses_total{route=\"telemeter-server-metrics-v1-receive\"}[$interval]))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"receive\"}[$interval])))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"receive\"}[$interval])))",
       "legendFormat": "90th"
      },
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"telemeter-server\",code!~\"5..\",handler=\"receive\"}[$interval])))",
       "legendFormat": "50th"
      }
     ]
    }
   ]
  },
  { "title": "Oauth Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Oauth Client Response Codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(\n   rate(client_api_requests_total{namespace=\"$namespace\",client=\"oauth\"}[$interval]),\n  \"status_code\", \"${1}xx\", \"code\", \"([0-9])..\"\n)) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Resource Usage: Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$namespace\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name!=\"\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Quota",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      },
      {
       "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"$namespace\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
      }
     ]
    }
   ]
  }
 ]
}