{
 "title": "Jaeger",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "span creation rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_tracer_reporter_spans_total{result=~\"dropped|err\", namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(jaeger_tracer_reporter_spans_total{namespace=\"observatorium-traces\"}[1m])) - sum(rate(jaeger_tracer_reporter_spans_total{result=~\"dropped|err\", namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "% spans dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_tracer_reporter_spans_total{result=~\"dropped|err\",namespace=\"observatorium-traces\"}[1m])) / sum(rate(jaeger_tracer_reporter_spans_total{namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "batch ingest rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_failures_total{namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_submitted_total{namespace=\"observatorium-traces\"}[1m])) - sum(rate(jaeger_agent_reporter_batches_failures_total{namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "% batches dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_agent_reporter_batches_failures_total{namespace=\"observatorium-traces\"}[1m])) by (cluster) / sum(rate(jaeger_agent_reporter_batches_submitted_total{namespace=\"observatorium-traces\"}[1m])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "span ingest rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_collector_spans_dropped_total{namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(jaeger_collector_spans_received_total{namespace=\"observatorium-traces\"}[1m])) - sum(rate(jaeger_collector_spans_dropped_total{namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "% spans dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_collector_spans_dropped_total{namespace=\"observatorium-traces\"}[1m])) by (instance) / sum(rate(jaeger_collector_spans_received_total{namespace=\"observatorium-traces\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Collector Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "span queue length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jaeger_collector_queue_length{namespace=\"observatorium-traces\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "span queue time - 95 percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jaeger_collector_in_queue_latency_bucket{namespace=\"observatorium-traces\"}[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "qps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jaeger_query_requests_total{result=\"err\", namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(jaeger_query_requests_total{namespace=\"observatorium-traces\"}[1m])) - sum(rate(jaeger_query_requests_total{result=\"err\", namespace=\"observatorium-traces\"}[1m]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "latency - 99 percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(jaeger_query_latency_bucket{namespace=\"observatorium-traces\"}[1m])) by (le, instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}