{
 "title": "Receive Overview",
 "panels": [
  {
   "title": "Rate of requests",
   "type": "graph",
   "description": "Shows rate of requests against Receive for the given time",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"receive\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against Receive.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"receive\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"receive\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"receive\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Replication request count",
   "type": "graph",
   "description": "Shows the number of replication requests against Receive.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, grpc_method, grpc_code) (rate(grpc_client_handled_total{grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Replication request duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle replication requests in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(grpc_client_handling_seconds_bucket{grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Replication request errors",
   "type": "graph",
   "description": "Shows the number of replication request errors.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_code) (rate(grpc_client_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval])) / ignoring (grpc_code) group_left() sum by (namespace, job) (rate(grpc_client_handled_total{grpc_type=\"unary\", grpc_method=\"RemoteWrite\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Concurrency gate utilization",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (pod) (http_inflight_requests{handler=\"receive\", namespace=\"$namespace\"})",
     "legendFormat": "concurrency gate used {{pod}}"
    },
    {
     "expr": "max by (pod) (thanos_receive_write_request_concurrency_write_request_limit{namespace=\"$namespace\"})",
     "legendFormat": "concurrency gate limit {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory working set",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{container=\"thanos-receive\", namespace=\"$namespace\"})",
     "legendFormat": "memory usage system {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"observatorium-thanos-receive-default\", namespace=\"$namespace\"}[$interval]) * 100",
     "legendFormat": "cpu usage system {{pod}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"thanos-receive\"})",
     "legendFormat": "pod restart count {{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-receive-.*\"}[$interval]))",
     "legendFormat": "network traffic in {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-receive-.*\"}[$interval]))",
     "legendFormat": "network traffic out {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Query Frontend Overview",
 "panels": [
  {
   "title": "Rate of requests",
   "type": "graph",
   "description": "Shows rate of requests against Query Frontend for the given time.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against Query Frontend.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query-frontend\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{container=\"thanos-query-frontend\", namespace=\"$namespace\"})",
     "legendFormat": "memory usage system {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"observatorium-thanos-query-frontend\", namespace=\"$namespace\"}[$interval]) * 100",
     "legendFormat": "cpu usage system {{pod}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container='thanos-query-frontend'}[$interval])",
     "legendFormat": "pod {{pod}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-query-frontend-.*\"}[$interval])",
     "legendFormat": "receive bytes pod {{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-query-frontend-.*\"}[$interval])",
     "legendFormat": "transmit bytes pod {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Query Overview",
 "panels": [
  {
   "title": "Instant Query Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query for the given time.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Instant Query Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Instant Query Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Range Query Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Range Query Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query_range.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Range Query Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Concurrent Capacity",
   "type": "graph",
   "description": "Shows available capacity of processing queries in parallel.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(thanos_query_concurrent_gate_queries_max{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]) - avg_over_time(thanos_query_concurrent_gate_queries_in_flight{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory working set",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{container=\"thanos-query\", namespace=\"$namespace\"})",
     "legendFormat": "memory usage system {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"observatorium-thanos-query\", namespace=\"$namespace\"}[$interval]) * 100",
     "legendFormat": "cpu usage system {{pod}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"thanos-query\"})",
     "legendFormat": "pod restart count {{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", container=\"thanos-query\", pod=~\"observatorium-thanos-query-.*\"}[$interval]))",
     "legendFormat": "network traffic in {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", container=\"thanos-query\", pod=~\"observatorium-thanos-query-.*\"}[$interval]))",
     "legendFormat": "network traffic out {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Ruler - Query Overview",
 "panels": [
  {
   "title": "Instant Query Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query for the given time.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Instant Query Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Instant Query Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Range Query Rate",
   "type": "graph",
   "description": "Shows rate of requests against /query_range for the given time range.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, handler, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{handler}} {{code}}"
    }
   ]
  },
  {
   "title": "Range Query Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests against /query_range.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, code) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\",code=~\"5..\"}[$interval])) / ignoring (code) group_left() sum by (namespace, job) (rate(http_requests_total{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Range Query Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(http_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", handler=\"query_range\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Concurrent Capacity",
   "type": "graph",
   "description": "Shows available capacity of processing queries in parallel.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(thanos_query_concurrent_gate_queries_max{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]) - avg_over_time(thanos_query_concurrent_gate_queries_in_flight{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{job}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory working set",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{container=\"thanos-query\", namespace=\"$namespace\"})",
     "legendFormat": "memory usage system {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"observatorium-thanos-query\", namespace=\"$namespace\"}[$interval]) * 100",
     "legendFormat": "cpu usage system {{pod}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"thanos-query\"})",
     "legendFormat": "pod restart count {{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-ruler-query-.*\"}[$interval]))",
     "legendFormat": "network traffic in {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-ruler-query-.*\"}[$interval]))",
     "legendFormat": "network traffic out {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Thanos Rule Overview",
 "panels": [
  {
   "title": "Total evaluations",
   "type": "graph",
   "description": "Displays the rate of total rule evaluations,",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, rule_group) (rate(prometheus_rule_evaluations_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{rule_group}}"
    }
   ]
  },
  {
   "title": "Failed evaluations",
   "type": "graph",
   "description": "Displays the rate of rule evaluation failures, grouped by rule group.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, rule_group) (rate(prometheus_rule_evaluation_failures_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{rule_group}}"
    }
   ]
  },
  {
   "title": "Evaluations with warnings",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, strategy) (rate(thanos_rule_evaluation_with_warnings_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{rule_group}}"
    }
   ]
  },
  {
   "title": "Too slow evaluations",
   "type": "graph",
   "description": "Displays the total time of rule group evaluations that took longer than their scheduled interval.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, rule_group) (prometheus_rule_group_last_duration_seconds{namespace=\"$namespace\", job=~\"$job\"}) / sum by(job, rule_group) (prometheus_rule_group_interval_seconds{namespace=\"$namespace\", job=~\"$job\"})",
     "legendFormat": "{{rule_group}}"
    }
   ]
  },
  {
   "title": "Rate of sent alerts",
   "type": "graph",
   "description": "Shows the rate of total alerts sent by Thanos.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_alert_sender_alerts_sent_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Rate of send alerts errors",
   "type": "graph",
   "description": "Displays the ratio of error rate to total alerts sent rate by Thanos.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(thanos_alert_sender_errors_total{namespace=\"$namespace\", job=~\"$job\"}[$interval])) / sum by (job) (rate(thanos_alert_sender_alerts_sent_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Duration od send alerts",
   "type": "graph",
   "description": "Displays the 50th, 90th, and 99th percentile latency of alert requests sent by Thanos.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(thanos_alert_sender_latency_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "MB" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{container=\"thanos-rule\", namespace=\"$namespace\"}) / (1024 * 1024)",
     "legendFormat": "memory usage system {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\", job=~\"$job\"}[$interval]) * 100",
     "legendFormat": "cpu usage system {{pod}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "MB" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-rule.*\"}[$interval]) / (1024 * 1024)",
     "legendFormat": "receive bytes pod {{pod}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-rule.*\"}[$interval]) / (1024 * 1024)",
     "legendFormat": "transmit bytes pod {{pod}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"thanos-rule\"}[$interval])",
     "legendFormat": "pod {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Store Gateway Overview",
 "panels": [
  {
   "title": "Unary gRPC Rate",
   "type": "graph",
   "description": "Shows rate of handled Unary gRPC requests from queriers.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, grpc_method, grpc_code) (rate(grpc_server_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Unary gRPC Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval])) / ignoring (grpc_code) group_left() sum by (namespace, job) (rate(grpc_server_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Unary gRPC Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"unary\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Sreamed gRPC Rate",
   "type": "graph",
   "description": "Shows rate of handled Streamed gRPC requests from queriers.",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace,  job, grpc_method, grpc_code) (rate(grpc_server_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))",
     "legendFormat": "{{namespace}} {{job}} {{grpc_method}} {{grpc_code}}"
    }
   ]
  },
  {
   "title": "Sreamed gRPC Errors",
   "type": "graph",
   "description": "Shows ratio of errors compared to the total number of handled requests from queriers.",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, grpc_code) (rate(grpc_server_handled_total{grpc_code=~\"Unknown|ResourceExhausted|Internal|Unavailable|DataLoss\",namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval])) / ignoring (grpc_code) group_left() sum by (namespace, job) (rate(grpc_server_handled_total{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Sreamed gRPC Duration",
   "type": "graph",
   "description": "Shows how long has it taken to handle requests from queriers, in quantiles.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=~\"$job\", grpc_type=\"server_stream\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Data Touched",
   "type": "graph",
   "description": "Show the size of data touched",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(thanos_bucket_store_series_data_touched{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P99: {{data_type}} / {{job}}"
    },
    {
     "expr": "sum by (namespace, job, data_type) (rate(thanos_bucket_store_series_data_touched_sum{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval])) / sum by (namespace, job, data_type) (rate(thanos_bucket_store_series_data_touched_count{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "mean: {{data_type}} / {{job}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(thanos_bucket_store_series_data_touched{namespace=\"$namespace\", job=~\"$job\"}[$__rate_interval])))",
     "legendFormat": "P50: {{data_type}} / {{job}}"
    }
   ]
  },
  {
   "title": "Get All",
   "type": "graph",
   "description": "Shows how long has it taken to get all series.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(thanos_bucket_store_series_get_all_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "description": "Shows how long has it taken to merge series.",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (namespace, job, le) (rate(thanos_bucket_store_series_merge_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p50 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.90, sum by (namespace, job, le) (rate(thanos_bucket_store_series_merge_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p90 {{namespace}} {{job}}",
     "logBase": 10
    },
    {
     "expr": "histogram_quantile(0.99, sum by (namespace, job, le) (rate(thanos_bucket_store_series_merge_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$job\"}[$interval]))) * 1",
     "legendFormat": "p99 {{namespace}} {{job}}",
     "logBase": 10
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory working set",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{container=\"thanos-store\", namespace=\"$namespace\"})",
     "legendFormat": "memory usage system {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"observatorium-thanos-store-.*\", namespace=\"$namespace\"}[$interval]) * 100",
     "legendFormat": "cpu usage system {{pod}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"thanos-store\"})",
     "legendFormat": "pod restart count {{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-store-.*\"}[$interval]))",
     "legendFormat": "network traffic in {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-thanos-store-.*\"}[$interval]))",
     "legendFormat": "network traffic out {{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "Alertmanager Overview",
 "panels": [
  {
   "title": "Alerts receive rate",
   "type": "graph",
   "description": "rate of successful and invalid alerts received by the Alertmanager",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(alertmanager_alerts_received_total{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) by (namespace,job,pod)",
     "legendFormat": "alerts received {{pod}}"
    },
    {
     "expr": "sum(rate(alertmanager_alerts_invalid_total{namespace=~\"$namespace\",job=~\"$job\"}[$__rate_interval])) by (namespace,job,pod)",
     "legendFormat": "alerts invalid {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "description": "Memory working set",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{container=\"observatorium-alertmanager\", namespace=\"$namespace\"})",
     "legendFormat": "memory usage system {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"observatorium-alertmanager.*\", namespace=\"$namespace\"}[$interval]) * 100",
     "legendFormat": "cpu usage system {{pod}}"
    }
   ]
  },
  {
   "title": "Pod/Container Restarts",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"$namespace\", container=\"observatorium-alertmanager\"})",
     "legendFormat": "pod restart count {{pod}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-alertmanager.*\"}[$interval]))",
     "legendFormat": "network traffic in {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"observatorium-alertmanager.*\"}[$interval]))",
     "legendFormat": "network traffic out {{pod}}"
    }
   ]
  }
 ]
}