apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: memcached
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: api-memcached
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: memcached
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: ""
    name: api-memcached
    namespace: rhobs-production
  spec:
    clusterIP: None
    ports:
    - name: client
      port: 11211
      protocol: TCP
      targetPort: 11211
    - name: metrics
      port: 9150
      protocol: TCP
      targetPort: 9150
    selector:
      app.kubernetes.io/component: api-memcached
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: memcached
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: ""
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: api-memcached
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: memcached
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: ""
    name: api-memcached
    namespace: rhobs-production
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    creationTimestamp: null
    labels:
      app.kubernetes.io/component: api-memcached
      app.kubernetes.io/instance: rhobs
      app.kubernetes.io/name: memcached
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: ""
    name: api-memcached
    namespace: rhobs-production
  spec:
    podManagementPolicy: OrderedReady
    replicas: 1
    selector:
      matchLabels:
        app.kubernetes.io/component: api-memcached
        app.kubernetes.io/instance: rhobs
        app.kubernetes.io/name: memcached
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: ""
    serviceName: api-memcached
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: api-memcached
          app.kubernetes.io/instance: rhobs
          app.kubernetes.io/name: memcached
          app.kubernetes.io/part-of: observatorium
          app.kubernetes.io/version: ""
      spec:
        containers:
        - args:
          - -m 2048
          - -c 3072
          - -I 5m
          - -v
          imagePullPolicy: IfNotPresent
          name: memcached
          ports:
          - containerPort: 11211
            name: client
            protocol: TCP
          resources: {}
          terminationMessagePolicy: FallbackToLogsOnError
        - args:
          - --memcached.address=localhost:11211
          - --web.listen-address=0.0.0.0:9150
          imagePullPolicy: IfNotPresent
          name: exporter
          ports:
          - containerPort: 9150
            name: metrics
            protocol: TCP
          resources: {}
        securityContext: {}
        serviceAccountName: api-memcached
    updateStrategy: {}
  status:
    availableReplicas: 0
    replicas: 0
